inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.10
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/triclops/**/*'
    - 'tmp/**/*'

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

# Metrics/BlockLength:
#   Exclude:
#     - 'spec/**/*'

# Layout/BlockEndNewline:
#   Exclude:
#     - 'spec/**/*'

# Layout/EmptyLinesAroundModuleBody:
#   Enabled: false

# Layout/EmptyLinesAroundBlockBody:
#   Enabled: false

# Layout/EmptyLinesAroundClassBody:
#   Enabled: false

# Layout/MultilineBlockLayout:
#   Exclude:
#     - 'spec/**/*'

# Metrics/LineLength:
#   Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
