require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude: []
  CountComments: false  # count full line comments?
  Max: 275

Metrics/ModuleLength:
  Exclude: []
  CountComments: false
  Max: 110

Metrics/ParameterLists:
  Max: 6

Naming/PredicateName:
  Exclude: []

Performance/Casecmp:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude: []

Style/LineEndConcatenation:
  Exclude: []

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude: []

Style/SignalException:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
