language: ruby
cache: bundler
sudo: false
dist: trusty

rvm:
  - 2.3.4
  - 2.4.2

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake json_csv:ci
